# Generated by Django 4.0 on 2021-12-09 17:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_alter_customerdetails_options_alter_order_payment_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='customerdetails',
            name='order',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='home.order'),
            preserve_default=False,
        ),
    ]
