# Generated by Django 4.0 on 2021-12-12 15:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_customerdetails_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customerdetails',
            name='order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='home.order'),
        ),
    ]
