# Generated by Django 4.0 on 2021-12-12 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_product_alter_customerdetails_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='package',
            field=models.IntegerField(default=0),
        ),
    ]
