# Generated by Django 4.0 on 2021-12-15 16:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0009_card'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='payment_id',
            new_name='payment_type',
        ),
    ]
