# Generated by Django 4.0 on 2021-12-15 16:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0010_rename_payment_id_order_payment_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='totalProducts',
        ),
        migrations.RemoveField(
            model_name='order',
            name='unitAmount',
        ),
        migrations.AddField(
            model_name='order',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='home.product'),
        ),
    ]
