# Generated by Django 4.0 on 2021-12-15 16:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0011_remove_order_totalproducts_remove_order_unitamount_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='card',
            name='order',
            field=models.OneToOneField(default=0, on_delete=django.db.models.deletion.CASCADE, to='home.order'),
            preserve_default=False,
        ),
    ]
