# Generated by Django 4.0 on 2021-12-16 15:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0012_card_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customerdetails',
            name='order',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='home.order'),
        ),
    ]
